# Generated by Django 5.2.16 on 2026-07-22 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivoKou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=200, verbose_name='Tit Nivo a')),
                ('deskripsyon', models.TextField(blank=True, verbose_name='Deskripsyon')),
            ],
            options={
                'verbose_name': 'Nivo Kou',
                'verbose_name_plural': 'Nivo Kou yo',
            },
        ),
        migrations.CreateModel(
            name='AkseEtidyan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_akse', models.BooleanField(default=False, verbose_name='Èske li gen aksè nan platfòm lan?')),
                ('not_admin', models.TextField(blank=True, null=True, verbose_name='Nòt sou elèv sa a')),
                ('etidyan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='akse', to=settings.AUTH_USER_MODEL, verbose_name='Elèv')),
            ],
            options={
                'verbose_name': 'Aksè Elèv',
                'verbose_name_plural': 'Aksè Elèv yo',
            },
        ),
        migrations.CreateModel(
            name='LesonKou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=255, verbose_name='Tit Leson an')),
                ('tip', models.CharField(choices=[('videyo', 'Videyo (Vimeo)'), ('odyo', 'Odyo (Audio/Listening)')], default='videyo', max_length=10, verbose_name='Tip Kontni')),
                ('vimeo_url', models.URLField(blank=True, null=True, verbose_name='Lyen Videyo Vimeo (Si se videyo)')),
                ('audio_url', models.URLField(blank=True, null=True, verbose_name='Lyen Odyo (Si se odyo)')),
                ('dire', models.CharField(max_length=50, verbose_name='Dire a (Eg: 01:50:08 oswa 15:30)')),
                ('nivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leson_yo', to='courses.nivokou', verbose_name='Nivo')),
            ],
            options={
                'verbose_name': 'Leson',
                'verbose_name_plural': 'Leson yo',
            },
        ),
    ]
