# Generated by Django 5.2.16 on 2026-07-22 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevPeman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metod_peman', models.CharField(choices=[('MonCash', 'MonCash'), ('Natcash', 'Natcash'), ('Zelle', 'Zelle'), ('Lòt', 'Lòt')], max_length=50)),
                ('nimewo_tranzaksyon', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_resi', models.ImageField(blank=True, null=True, upload_to='resi_peman/')),
                ('date_voye', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
