# Generated by Django 5.2.16 on 2026-07-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_verifikasyonemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesonkou',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='lesonkou',
            name='vimeo_url',
        ),
        migrations.AddField(
            model_name='lesonkou',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesonkou',
            name='fichye_odyo',
            field=models.FileField(blank=True, help_text='Upload yon fichye odyo (.mp3, .wav)', null=True, upload_to='odyo_leson/'),
        ),
        migrations.AddField(
            model_name='lesonkou',
            name='fichye_videyo',
            field=models.FileField(blank=True, help_text='Upload yon fichye videyo (.mp4)', null=True, upload_to='videyo_leson/'),
        ),
        migrations.AddField(
            model_name='lesonkou',
            name='lyen_videyo',
            field=models.URLField(blank=True, help_text='Oswa kole yon lyen videyo (YouTube, Vimeo, Google Drive, elatriye)', null=True),
        ),
    ]
