# Generated by Django 5.2.16 on 2026-07-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesonkou_audio_url_remove_lesonkou_vimeo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnstriksyonPeman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimewo_moncash', models.CharField(blank=True, help_text='Egzanp: +509 3400-0000', max_length=50, null=True)),
                ('nimewo_natcash', models.CharField(blank=True, help_text='Egzanp: +509 4300-0000', max_length=50, null=True)),
                ('enfomasyon_bank', models.TextField(blank=True, help_text='Egzanp: Unibank: 123-4567-8901 (Non sou kont lan)', null=True)),
                ('note_enpotan', models.TextField(blank=True, help_text='Ti enstriksyon pou etidyan an (egzanp: Antre nimewo tranzaksyon an presizeman)', null=True)),
            ],
            options={
                'verbose_name': 'Enstriksyon Peman',
                'verbose_name_plural': 'Enstriksyon Peman yo',
            },
        ),
    ]
