# Generated by Django 5.2.16 on 2026-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enstriksyonpeman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=200)),
                ('konsiy', models.TextField(help_text='Esplike sa eleman yo dwe fè nan devwa sa a')),
                ('fichye_dokiman', models.FileField(blank=True, help_text='Si se yon PDF/Word', null=True, upload_to='devwa/dokiman/')),
                ('fichye_odyo', models.FileField(blank=True, help_text='Si se yon odyo pou yo koute (.mp3)', null=True, upload_to='devwa/odyo/')),
                ('lyen_videyo', models.URLField(blank=True, help_text='Lyen videyo (YouTube, Drive, etc.)', null=True)),
                ('fichye_videyo', models.FileField(blank=True, help_text='Si se yon fichye videyo monte (.mp4)', null=True, upload_to='devwa/videyo/')),
                ('date_limit', models.DateTimeField(help_text='Dat ak lè devwa sa a dwe remèt')),
            ],
            options={
                'verbose_name_plural': 'Devwa yo',
            },
        ),
        migrations.CreateModel(
            name='Dokiman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=200)),
                ('fichye', models.FileField(upload_to='dokiman_kou/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_kreye', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Dokiman yo',
            },
        ),
        migrations.CreateModel(
            name='Tes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_minit', models.IntegerField(default=30, help_text='Temps tès la ap dure (an minit)')),
                ('lyen_tes', models.URLField(blank=True, help_text='Lyen tès la (Google Forms / Microsoft Forms / Platfòm)', null=True)),
            ],
            options={
                'verbose_name_plural': 'Tès ak Egzamen yo',
            },
        ),
    ]
