# Generated by Django 5.2.16 on 2026-07-24 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_devwa_dokiman_tes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=255, verbose_name='Tit Kou a')),
                ('deskripsyon', models.TextField(blank=True, verbose_name='Deskripsyon')),
                ('nivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kours', to='courses.nivokou', verbose_name='Nivo')),
            ],
            options={
                'verbose_name': 'Kou',
                'verbose_name_plural': 'Kou yo',
            },
        ),
        migrations.CreateModel(
            name='Setifika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichye_pdf', models.FileField(upload_to='setifika_pdf/')),
                ('date_emisyon', models.DateField(auto_now_add=True)),
                ('eleun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.kou')),
            ],
        ),
    ]
